### ISSUE TITLE
Can't install aniyomi 

### ISSUE THREAD

**Issue by Xb1te** [jmir1/aniyomi-website#65]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

1.tap the link from the site
2.tap to install 
3.tap the file that is downloaded by the link
4.tap install 
4.error

### Expected behavior

To install aniyomi to my phone

### Actual behavior

I downloaded the aniyomi app but when I tried to install it I said that it is not installed I can't see the app in my home screen even if I wait for a bit.

### Other details

![Screenshot_2022-04-13-15-06-26-574_com google android packageinstaller](https://user-images.githubusercontent.com/84349923/163176592-6e9c073b-67d0-4d71-b7a6-79f892e10212.jpg)

**Comment by Xb1te** [comment]
Please help don't just close the conversation

**Comment by GMRobo** [comment]
@Xb1te I believe that this is an android issue, have you tried a different version (arm or armeabi) as installs have failed for me if I choose the wrong one. This is also the wrong repo to post this issue to, thus why @jmir1 closed it.
